version: '3.8'

services:

  chessback:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./project:/usr/src/app
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql+asyncpg://makrogol:1234@127.0.0.1:5432/chess_db
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=makrogol
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=chess_db