version: '3.8'

services:
  chessback:
    build: .
    container_name: chessback
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    expose:
      - $DB_PORT
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: null
